//! Record conversation items and attach the producing model's provenance.

use super::session::Session;
use super::turn_context::TurnContext;
use codex_history::ResponseItemEnvelope;
use codex_protocol::models::ResponseItem;
use codex_protocol::openai_models::ModelInfo;

impl Session {
    /// Appends to history, persists the prepared items, then notifies raw-item observers.
    /// Execution callers supply their captured model; standalone callers need no tool runtime.
    #[tracing::instrument(level = "trace", skip_all, fields(item_count = items.len()))]
    pub(crate) async fn record_conversation_items(
        &self,
        turn_context: &TurnContext,
        model_info: &ModelInfo,
        items: &[ResponseItem],
    ) {
        self.record_items_with_provenance(turn_context, model_info, items, None)
            .await;
    }

    /// Same as [`Session::record_conversation_items`], for items generated by
    /// the model in the turn that just ran: each envelope additionally records
    /// the wire/bridge/provider/model captured from the producing request
    /// (fork extension). Native first-party transports stay unannotated —
    /// there is no cross-protocol projection to prepare for them.
    #[tracing::instrument(level = "trace", skip_all, fields(item_count = items.len()))]
    pub(crate) async fn record_model_generated_items(
        &self,
        turn_context: &TurnContext,
        model_info: &ModelInfo,
        items: &[ResponseItem],
    ) {
        let provenance = self.model_output_provenance(model_info).await;
        self.record_items_with_provenance(turn_context, model_info, items, provenance)
            .await;
    }

    /// Provenance snapshot from the CURRENT request context. Only bridged
    /// providers record it; resume never recomputes this for old items.
    async fn model_output_provenance(
        &self,
        model_info: &ModelInfo,
    ) -> Option<codex_history::ModelOutputProvenance> {
        let info = self.provider().await;
        if !info.uses_model_bridge() {
            return None;
        }
        let bridge = match info.experimental_bridge {
            Some(codex_model_provider_info::ChatBridge::Genai) => "genai",
            Some(codex_model_provider_info::ChatBridge::Rig)
            | Some(codex_model_provider_info::ChatBridge::Native)
            | None => "rig",
        };
        Some(codex_history::ModelOutputProvenance {
            wire_protocol: info.wire_api.to_string(),
            bridge: Some(bridge.to_string()),
            provider: Some(info.name),
            model: Some(model_info.slug.clone()),
        })
    }

    async fn record_items_with_provenance(
        &self,
        turn_context: &TurnContext,
        model_info: &ModelInfo,
        items: &[ResponseItem],
        provenance: Option<codex_history::ModelOutputProvenance>,
    ) {
        let (items, image_preparations) = self
            .prepare_conversation_items_for_history(turn_context, model_info, items)
            .await;
        let mut items: Vec<ResponseItemEnvelope> = items
            .into_owned()
            .into_iter()
            .map(ResponseItemEnvelope::new)
            .collect();
        if let Some(provenance) = provenance {
            for envelope in &mut items {
                envelope
                    .metadata
                    .get_or_insert_default()
                    .model_output_provenance = Some(provenance.clone());
            }
        }
        self.record_prepared_conversation_items(
            turn_context,
            model_info,
            items,
            image_preparations,
        )
        .await;
    }
}
